#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number
index:
    path: /
    controller: App\Controller\Zkpd3Controller::index
